### ISSUE TITLE
100% Firefox process caused by allow-right-click extension

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [lunu-bounir/allow-right-click.html#18]
I have a curious problem with Firefox and Allow-Right-Click-0.4.2 extension on Arch Linux.

Whenever I start Firefox, there's always one firefox process (according to htop) which consumes 100% of one core. If I disable allow-right-click extension for a few seconds and re-enable it, the process in question disappears, and Firefox and the extension continue working without issues for the rest of the day. If I allow the offending process to run for a few hours, Firefox eventually (partially) freezes and needs to be restarted. Next time I start Firefox the cycle starts again.

**Comment by lunu-bounir** [comment]
To debug:
1. Open the browser console and see if you have any unusual errors
2. Try the extension on a [clean profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles) and see if this behavior persists

Do you have the automatic injection feature enabled?

**Comment by voxitme** [comment]
I have the same issue, even if on a ryzen 5600x, it takes roughly 17-19%.

- Only happens if Firefox is started with the extension already enabled and in this situation, stops right when deactivated while Firefox still runs.

- Doesn't happen if extension is disabled before starting Firefox, and then enabed it and activated while Firefox is running. In this case, the extension works fine and doesnt lead to any cpu overusage.
