### ISSUE TITLE
Addon suddenly stopped working on a website.

### ISSUE THREAD

**Issue by bulgewater** [lunu-bounir/allow-right-click.html#20]
Hello there!

First of all, thank you for making and maintaining this addon. I use it a lot, it's fantastic.

However, today it stopped working on a website. It's an adult one though, so leaving the link might get me in trouble. But here it is anyway: https://thisvid.com/
I was using it on said website, when all of a sudden it stopped working, not letting me right-click and save videos. I'd be really grateful if you could take a look at it.

Thank you in advance.

**Comment by bulgewater** [comment]
Note: I rerolled to the previous version and it's working this way. Gonna keep using the old version until a possible fix. :) Thanks again!

**Comment by lunu-bounir** [comment]
Give the new commit a try and let me know if the issue is fixed or not

1. Download https://github.com/lunu-bounir/allow-right-click.html/archive/refs/heads/master.zip
2. Extract it into a directory
3. Open chrome://extensions and turn the developer mode on
4. Drop the "v2" directory to the view. 

You should have the extension on the action area.

**Comment by bulgewater** [comment]
It is working indeed! Thank you.

I completely forgot to mention that I normally use the addon with Firefox instead of Chrome. Is it possible to somehow apply this fix to the Firefox browser? Apologies for being so problematic...

**Comment by lunu-bounir** [comment]
It should work on FF too. Just start with about:debugging#/runtime/this-firefox
